package com.rtsbuilding.rtsbuilding.network;

import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.relauncher.Side;

public final class RtsNetworkManager {

    private static final String CHANNEL = "rtsbuilding";
    public static final SimpleNetworkWrapper NETWORK = new SimpleNetworkWrapper(CHANNEL);

    private RtsNetworkManager() {}

    public static void registerMessages() {
        int disc = 0;

        // ---- Camera (3 messages) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.camera.C2SRtsToggleCameraMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.camera.C2SRtsToggleCameraMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.camera.C2SRtsCameraMoveMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.camera.C2SRtsCameraMoveMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.camera.S2CRtsCameraStateMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.camera.S2CRtsCameraStateMessage.class,
            disc++,
            Side.CLIENT);

        // ---- Builder (17 messages) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsSetModeMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsSetModeMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsRotateBlockMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsRotateBlockMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsPlaceMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsPlaceMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsPlaceBatchMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsPlaceBatchMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsPlaceFluidMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsPlaceFluidMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsStoreFluidMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsStoreFluidMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsInteractMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsInteractMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsQuickDropMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsQuickDropMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsBreakMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsBreakMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsMineMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsMineMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsUltimineMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsUltimineMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsAreaMineMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsAreaMineMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsAreaDestroyMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.C2SRtsAreaDestroyMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsMineProgressMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsMineProgressMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsPlaceAnimationMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsPlaceAnimationMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsBreakAnimationMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsBreakAnimationMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsUltimineProgressMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.builder.S2CRtsUltimineProgressMessage.class,
            disc++,
            Side.CLIENT);

        // ---- Craft (9 messages) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsCraftRecipeMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsCraftRecipeMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsCraftRefillMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsCraftRefillMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsJeiTransferMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsJeiTransferMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsOpenCraftTerminalMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsOpenCraftTerminalMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsRequestCraftablesMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.C2SRtsRequestCraftablesMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.S2CRtsCraftablesMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.S2CRtsCraftablesMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.S2CRtsCraftFeedbackMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.S2CRtsCraftFeedbackMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.craft.S2CRtsOpenCraftTerminalMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.craft.S2CRtsOpenCraftTerminalMessage.class,
            disc++,
            Side.CLIENT);

        // ---- Feedback (1 message) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.feedback.S2CRtsDamageFeedbackMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.feedback.S2CRtsDamageFeedbackMessage.class,
            disc++,
            Side.CLIENT);

        // ---- Progression (11 messages) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsBeginHomeSelectionMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsBeginHomeSelectionMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsQuestDetectMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsQuestDetectMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsRequestProgressionStateMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsRequestProgressionStateMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsSetHomeMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsSetHomeMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsSetProgressionCostMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsSetProgressionCostMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsSetSurvivalProgressionMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsSetSurvivalProgressionMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsUnlockProgressionNodeMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.C2SRtsUnlockProgressionNodeMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.S2CRtsProgressionStateMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.S2CRtsProgressionStateMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.progression.S2CRtsQuestDetectStatusMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.progression.S2CRtsQuestDetectStatusMessage.class,
            disc++,
            Side.CLIENT);

        // ---- Storage (23 messages) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsCloseRemoteMenuMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsCloseRemoteMenuMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsFillInventoryMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsFillInventoryMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsFunnelTargetMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsFunnelTargetMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsImportMenuSlotMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsImportMenuSlotMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsLinkedPickupMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsLinkedPickupMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsLinkedQuickMoveMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsLinkedQuickMoveMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsLinkStorageMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsLinkStorageMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsOpenGuiBindingMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsOpenGuiBindingMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsRequestStoragePageMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsRequestStoragePageMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsReturnCarriedMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsReturnCarriedMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetAutoStoreMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetAutoStoreMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsSetAutoStoreMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsSetAutoStoreMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetBdNetworkMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetBdNetworkMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetFunnelMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetFunnelMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetGuiBindingMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetGuiBindingMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetQuickSlotMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsSetQuickSlotMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsStoreHotbarSlotMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsStoreHotbarSlotMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsUnlinkStorageMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsUnlinkStorageMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsUpdateLinkedStorageMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.C2SRtsUpdateLinkedStorageMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsRemoteMenuHintMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsRemoteMenuHintMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsStoragePageMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsStoragePageMessage.class,
            disc++,
            Side.CLIENT);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsLinkStorageStatusMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.network.storage.S2CRtsLinkStorageStatusMessage.class,
            disc++,
            Side.CLIENT);

        // ---- Blueprint (2 messages) ----
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.blueprint.network.C2SBlueprintPlaceMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.blueprint.network.C2SBlueprintPlaceMessage.class,
            disc++,
            Side.SERVER);
        NETWORK.registerMessage(
            com.rtsbuilding.rtsbuilding.blueprint.network.S2CBlueprintStatusMessage.Handler.class,
            com.rtsbuilding.rtsbuilding.blueprint.network.S2CBlueprintStatusMessage.class,
            disc++,
            Side.CLIENT);
    }
}
